language: python

branches:
  except:
    - gh-pages

python:
  - "2.7"

install:
  - pip install tox

script:
  - tox

env:
  matrix:
    - TOXENV=py26
    - TOXENV=py27
    - TOXENV=py32
    - TOXENV=py33
    - TOXENV=pep8

matrix:
  allow_failures:
    - env: TOXENV=py32
    - env: TOXENV=py33
